### ISSUE TITLE
incompatible with webpack 5.47.0

### ISSUE THREAD

**Issue by neelance** [xz64/license-webpack-plugin#106]
Starting with https://github.com/webpack/webpack/releases/tag/v5.47.0 the plugin throws the error `TypeError: item.node is not a function`.

I think this can be quickly resolved by upgrading the dependency `webpack-sources` to its latest version.

**Comment by xz64** [comment]
Yes it does seem to work after upgrading webpack-sources. However I will need to drop support for webpack versions earlier than 4, so this will be a major change. I will update this issue once this is fixed

**Comment by bryanchen-d** [comment]
Hi @xz64 , any updates on this issue?

**Comment by xz64** [comment]
Fixed in v3.0.0 (please note that even though this is a major version change, most builds don't need to change anything. I did not drop support for webpack versions earlier than 5)
