### ISSUE TITLE
Improve pathExists and isDirectory performance once graceful-fs supports it

### ISSUE THREAD

**Issue by markjm** [xz64/license-webpack-plugin#109]
Once this change is merged: https://github.com/isaacs/node-graceful-fs/issues/221, stop throwing errors in below places:
https://github.com/xz64/license-webpack-plugin/blob/e70c57b0505792d9316f2a798a151c0262fa8565/src/WebpackFileSystem.ts#L21

https://github.com/xz64/license-webpack-plugin/blob/e70c57b0505792d9316f2a798a151c0262fa8565/src/WebpackFileSystem.ts#L47

Since we expect this can be null, we skip a lot of overhead in creating these errors. Skipping these errors is over a 3x speedup for these calls
https://github.com/nodejs/node/pull/33716

**Comment by xz64** [comment]
Implemented by @markjm  in #114
