### ISSUE TITLE
Support inclusion of extra licenses

### ISSUE THREAD

**Issue by SchnWalter** [xz64/license-webpack-plugin#110]
It would be nice to have an option to allow **extraLicenses** to be included in the output file. It could either receive a directory where the file names (without extension) would be used as names; or the option could accept a map of name and license file path.

This is particularly useful for MIT where you are required to include the copyright notice when using "significant portions" of a project that doesn't have any license information inside the used/copied files.

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Thank you!

**Comment by xz64** [comment]
You can customize the `renderLicenses` option to add additional freeform text to the output
