### ISSUE TITLE
Produce license file for each entry point/bundle

### ISSUE THREAD

**Issue by rhys-e** [xz64/license-webpack-plugin#13]
I'd like to be able to produce a license manifest for each entry point/bundle processed by webpack and output the file alongside the bundle ${filename}.

It'd also be really useful to be able to add a comment to the top of the given bundle pointing towards the generated license manifest for that bundle (without having to rely on other plugins to do this). 

Looking at the plugins options I don't seem to see a way to managing this as of now.

Thanks

**Comment by xz64** [comment]
I will take care of this in #14 as #14 has a dependency on producing license files this way.

**Comment by xz64** [comment]
@rhys-e  I have implemented this functionality in the dev branch. Please try it out and let me know if you have any questions.

**Comment by rhys-e** [comment]
@xz64 Thanks - I've tried it out and it's working nicely except for two issues I'm noticing:

1.  Something's going wrong with the character encoding, e.g. double quotations are coming out in the license file as the string of the ASCII character (" => `&#34;`)

2. I've got 3 entry points in my webpack config. This results in 3 license files as expected however, only two license files contain the actual webpack license. All 3 outputted src files contain the webpack bootstrap, so I'd expect to see the webpack license in all 3 license files. I'm not sure why the 3rd entry point would be special in any way.

I've got a general question as well: what's your suggested strategy for bundling the entire project's license (i.e. not 3rdparty). To me it makes sense to also include this in the external license file to reduce impact on the outputted minified js, in which case it'd be helpful to have the plugin also pull in the project's license file.

Thanks

**Comment by filipesilva** [comment]
Heya @xz64, is it still possible to produce a single licenses file, or does it have to be one license file for each bundle?

**Comment by xz64** [comment]
@rhys-e  I pushed a fix for the character encoding issue. Does your third entry reference any modules (via import/require statements) from node_modules?

Bundling the license of the project itself can be done with file-loader (basically copies your license file to your build output), but it will output the license to a separate file. I will consider adding an option to output first party license to each chunk later on.

@filipesilva   The plugin won't be able to generate a single license file unless it relies on the 'done' phase of the webpack compiler. Relying on the 'done' phase however will bring up the issue you described in #14 . I might be able to rely on some sort of mkdirp functionality to work around that issue though.

**Comment by rhys-e** [comment]
@xz64 re: 3rd module - it does reference other things from node_modules

**Comment by xz64** [comment]
@rhys-e  Can you share the webpack stats for your build? (If you are not sure how to generate the stats, please refer here: https://webpack.js.org/api/stats/ )

**Comment by rhys-e** [comment]
@xz64 quick note - If I do nothing in my code except import jquery then I get just the jquery license in the output, whereas if I import bowser I get both bowser's license and webpack's license. Both outputted bundles include the webpack bootstrapper as you'd expect.

Is adding the webpack license handled in some special way by the plugin? (since no-one has an import on webpack per se).

(My 3rd module isn't CSS, just a standard js module. I've boiled it down to a single file with a single import and seeing different behaviour depending on what I'm importing re: the inclusion of the webpack license or not).

**Comment by xz64** [comment]
@rhys-e  I see now. I had misunderstood the issue. You are expecting the license for webpack itself to be included since webpack inserts its own module loading code into your bundle. I checked out the bowser package. It looks like bowser is using a UMD build which is causing webpack's amd "define" function stub ( node_modules/webpack/buildin/amd-define.js ) to be loaded.

The plugin has no special logic for webpack. It just goes by whatever webpack reports in the chunk info. Perhaps I can add an option to force certain packages to be included in every license output. Overall webpack is just bundling your dependencies together, so I don't see a strong reason for including the license for webpack itself into the build.

**Comment by filipesilva** [comment]
@xz64 I had a go at this change and wanted to mention it makes empty files for bundles with no licenses. I added a PR to fix that https://github.com/xz64/license-webpack-plugin/pull/17.

**Comment by rhys-e** [comment]
@xz64 I suspected it might be something along those lines. I would say though that in all cases webpack does leave a bit of code in the outputted bundle (the webpack bootstrap) which would be the case for including its license I guess.

**Comment by xz64** [comment]
@rhys-e  I have made a change in the dev branch which allows you to force certain packages to be in the output. Please try it out and let me know how it goes.

**Comment by xz64** [comment]
Producing license file per chunk is is the default behavior in v1 now. (published now)

**Comment by rhys-e** [comment]
Tried out the additionalPackages flag, works fine :+1:
