### ISSUE TITLE
Output path not being created recursively

### ISSUE THREAD

**Issue by filipesilva** [xz64/license-webpack-plugin#14]
Heya,

If the webpack configuration has a deep output path that doesn't currently exist, `license-webpack-plugin` will fail at `mkdirSync` (https://github.com/angular/angular-cli/issues/7203).

Webpack itself is ok with creating this path and putting files there though. Perhaps `compilation.assets` could be used instead of `mkdirSync`? There's an example at https://github.com/webpack/docs/wiki/how-to-write-a-plugin#a-simple-example where they do that. That way Webpack itself would take care of outputting it.

**Comment by xz64** [comment]
In order to get access to the `compilation` object I will need to refactor the plugin to hook into the `emit` phase of webpack. I will try out your suggestion.

**Comment by xz64** [comment]
@filipesilva  I have pushed some updates to the dev branch. Please try it out and let me know if you run into any issues. There is a migration guide at MIGRATION.md for some breaking changes.

**Comment by filipesilva** [comment]
Hi @xz64, I can confirm that using the dev branch this bug does not manifest anymore.
