### ISSUE TITLE
Add a string or json module

### ISSUE THREAD

**Issue by WorldMaker** [xz64/license-webpack-plugin#16]
I'd like to add the 3rd Party License information directly into a Help or About page, so that the information is viewable within the app itself.

It would be great if this plugin (or one like it) could add a module to the webpack build returning the text as a string or maybe a more structured JSON file broken down by library name or similar to allow for even better user experience options (table of contents, etc).

**Comment by xz64** [comment]
@WorldMaker  I have made some changes in the dev branch to allow custom rendering via ejs template, so you can format the packages any way you like. Please try it out and let me know if you run into any issues.

**Comment by WorldMaker** [comment]
Using an ejs template looks like a step in the right direction. I think I'd still like some way to add it as a module or chunk directly inside the pack rather than a separate file/asset. Right now the easiest way I can see to pull in the txt file into my SPA app would be an `<iframe>` tag, but what I really would like is a way to `import licenses from 'licenses'` and use that in my application.

**Comment by xz64** [comment]
@WorldMaker  The tricky thing here is that there is no 'licenses' file to import at compile-time in webpack. The file gets generated after your modules are compiled. I think going XMLHttpRequest is the right way to  go here.

**Comment by WorldMaker** [comment]
I suppose I don't know the webpack model well enough to know how "late" you can add a module or if there are tricks something like add an empty module early and then "fill" it with a chunk at the end. XHR is fine for now.
