### ISSUE TITLE
Some licenses missing when using @angular/cli

### ISSUE THREAD

**Issue by michael42** [xz64/license-webpack-plugin#19]
Hi there,

we're using the Angular CLI, which builds a `3rdpartylicenses.txt` by default using license-webpack-plugin.

However, the licenses of some dependencies are missing in the output. I uploaded a rather minimal [Angular CLI-based reproduction repository](https://github.com/michael42/license-webpack-plugin-some-licenses-missing). In its `build/3rdpartylicenses.txt`, there is no entry for `@ngx-translate/http-loader` (or core), despite both being imported from `src/app/app.module.ts`.

When I debugged the issue (in a larger project where `@ngx-translate/core` is listed, but `@ngx-translate/http-loader` isn't) I found out that webpack uses different kinds of modules per compilation chunk. "Regular" dependencies were represented as a `NormalModule` with a `resource` from which the plugin uses to determine the package name. The dependencies that weren't included are contained in a `ConcatenatedModule`, which (in my case) had a reference `rootModule` to a `NormalModule` with a `resource`.

I tried building a minimal repo without Angular CLI, but that did work and included all dependencies. I assume its an interaction with one of the many other plugins (maybe ModuleConcatenationPlugin?) that the Angular CLI uses (`ng eject` creates a webpack.config.js).

**Comment by xz64** [comment]
@michael42  Thanks for the analysis. I have pushed a fix in version 1.0.2
