### ISSUE TITLE
Add new option

### ISSUE THREAD

**Issue by cakeinpanic** [xz64/license-webpack-plugin#2]
I'd like to have ability to provide my own pattern of output.
For example: 
`%name%@%version% type: %license%` url: %url%

**Comment by xz64** [comment]
I'd be willing to review a pull request for a change that uses [ejs](http://www.embeddedjs.com/) templates to generate the output file.

**Comment by xz64** [comment]
@cakeinpanic  Check out the dev branch. You can use ejs templates to configure the output.

**Comment by xz64** [comment]
I just published v1, which as the option of customizing the output via ejs template.
