### ISSUE TITLE
Mixed line endings

### ISSUE THREAD

**Issue by ln-e** [xz64/license-webpack-plugin#20]
For example webpack itself have CRLF windows line endings in license file. While other packages have unix-like LF line endigns. 
So generated 3rdpartylicenses.txt have a mixed line endings. 

Such files conflict with git's autocrlf option for example.

**Comment by xz64** [comment]
3rdpartylicenses.txt is a generated file, so normally it wouldn't be committed (it would be ignored via .gitignore instead) in git. Can you explain why you would want to commit this file into a git repository?

**Comment by ln-e** [comment]
In our case, we commited the build in the repository. Please, do not ask why, there is a rather complicated deployment =)

Nevertheless commit we build files or not, it does not seem to me that generating a file with mixed line endings is exactly how it was designed.

**Comment by xz64** [comment]
Fixed in version 1.2.0
