### ISSUE TITLE
module directory should be an option

### ISSUE THREAD

**Issue by gregorym** [xz64/license-webpack-plugin#22]
We should be able to override the moduleDirectory (Default to node_modules). It is possible to have node modules installed elsewhere than in node_modules.

**Comment by xz64** [comment]
I will need to make some assumptions to implement this:
1. node_modules will exist
2. devDependencies will be stored in node_modules

Let me know if these assumptions hold for your project.

**Comment by gregorym** [comment]
I am working on a PR. I'll send it later this week.

**Comment by gregorym** [comment]
After looking at your code I would need to do the following:
- moduleDirectory needs to be a plugin option that would default to `node_modules`
- buildRoot needs to be a plugin option as well.  Defaults to `findBuildRoot` when undefined

**Comment by xz64** [comment]
Sounds good

**Comment by xz64** [comment]
@gregorym  I have implemented this on the dev branch. Can you try it out on your project and let me know if it works out for you?

Steps to install:
1. Clone this repo
2. checkout the dev branch
3. run `npm install && npm run build && npm pack`
4. In your project directory, run `npm install /path/to/license-webpack-plugin-1.1.2.tgz` file

**Comment by gregorym** [comment]
Thanks @xz64. I will try next week :)

**Comment by xz64** [comment]
@gregorym  Did you get a chance to test it out?

**Comment by xz64** [comment]
Added feature in v1.2.0

Let me know if you run into any issues.
