### ISSUE TITLE
How to preppend license to the bundled file?

### ISSUE THREAD

**Issue by ktalebian** [xz64/license-webpack-plugin#28]
I'm trying to have the license text pre-pended to the the bundled file, and not as a separate file. How can this be achieved?

**Comment by xz64** [comment]
Currently this is not possible. I can take a look at implementing this some time though

**Comment by xz64** [comment]
added this feature in v1.3.0

add `<%- licenseInfo %>` in the bannerTemplate to use it

**Comment by PhilippWendler** [comment]
It seems this feature is not available anymore in version 2.0 since the migration to `renderBanner`? Could you please re-add this? That would be great!

**Comment by xz64** [comment]
You can write a renderBanner function that does the same thing the old version did.
