### ISSUE TITLE
How to whitelist license or package

### ISSUE THREAD

**Issue by agentschmitt** [xz64/license-webpack-plugin#29]
I want to fail my build when package with GPL license only is found. This works with the config below.
But i have one package "normalize-scss" with license "MIT or GPL-2.0".

Could we have a overridePattern that explicit allows licenses. (eg. overridepattern /MIT/).

Or maybe allow a function for accept license checks which could replace regex option, this would allow custom code for special use cases.

new LicenseWebpackPlugin({
  pattern: /.*/,
  unacceptablePattern: /GPL/,
  abortOnUnacceptableLicense: true
});

**Comment by xz64** [comment]
I like the function idea. I'll see what I can do

**Comment by xz64** [comment]
Hey just wanted to give you an update: I am planning on releasing a new major version which will support this feature

**Comment by xz64** [comment]
Closing this as there is a published release with this feature
