### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by 0xs** [xz64/license-webpack-plugin#3]
This plugin interprets every .js and .ts file path which is outside of the node_modules directory as a module called `C:` on Windows and crashes with an error:

> Error: ENOENT: no such file or directory, open 'C:\dev\site\example\node_modules\C:\package.json'

The problem seems to be in the `findPackageName` function. What I don't understand is that why does it consider files outside of the node_modules directory in the first place?

**Comment by xz64** [comment]
Do you have a sample repository I can debug this with? If not I can create a sample project but it may take more time.

**Comment by 0xs** [comment]
I set up a minimal example project [here](https://github.com/0xs/license-webpack-plugin-debug). It is a frankenstein mashup of the Angular 2 quickstart example project and an actual stripped down webpack production configuration I use in a real project.

**Comment by xz64** [comment]
I was getting this error on Windows 10: `EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'ts' in 'C:\Users\Me\git\license-webpack-plugin-debug'`

It appears to be a problem with your module resolution in webpack, as I have turned off the LicenseWebpackPlugin in your sample repo and still got the error.

In NodeJS, if a module cannot be resolved, it will keep searching the parent directories' `node_modules` folder (if it exists) until it reaches the file system root.

Let me know if I am missing something here.

**Comment by 0xs** [comment]
Sorry about that. It seems that `ts-loader` was missing from `package.json` and it's been included now. I tested it this time by removing the node_modules directory so it should work if LicenseWebpackPlugin is commented out and otherwise fail the right way.

**Comment by xz64** [comment]
Try version 0.2.1 and let me know if it works. Looks like I was not ignoring files coming outside of node_modules.
