### ISSUE TITLE
Feature Request: Use compiler.outputFileSystem

### ISSUE THREAD

**Issue by mwaldstein** [xz64/license-webpack-plugin#34]
While less common, I was in a scenario where I wanted to run a development server using a production configuration using webpack-dev-middleware. While native webpack outputs went into its MemoryFS, license-webpack-plugin still wrote to the native filesystem.

This is a low priority, but it would be nice if the compiler's outputFileSystem were used for writing if set in the compiler object.

While not applicable to my case, I suspect that supporting inputFileSystem might be appropriate.

References:

 * https://webpack.js.org/api/node/#custom-file-systems
 * https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L56

**Comment by xz64** [comment]
This should be doable in the next major release which I am working on.

**Comment by mwaldstein** [comment]
Just a heads up - the prerender-spa webpack plugin recently made this change as well.

Their commit for reference: https://github.com/chrisvfritz/prerender-spa-plugin/commit/dcdc518f39aa3f70a65762e87129b856a2416055

**Comment by xz64** [comment]
Published this in v2.0.0-alpha.6
