### ISSUE TITLE
Tests failing on windows in a fresh fork

### ISSUE THREAD

**Issue by johannao76** [xz64/license-webpack-plugin#35]
I forked the repo just now and getting an error when running npm test. I am using node 8.9.4. Full test run output below:
![image](https://user-images.githubusercontent.com/11838969/40864026-eed89a16-65a6-11e8-866c-dac7954ed0c9.png)

**Comment by xz64** [comment]
From the screenshot it appears you might be on Windows.

Unit tests don't run properly on Windows. I had tried to make it work but ran into some issue with mock-fs : https://github.com/tschaub/mock-fs/issues/201 

Next major release (you can try it out by installing license-webpack-plugin@next) should be able to run on windows but I haven't tested it.

**Comment by johannao76** [comment]
I will try to get to it this weekend.

**Comment by johannao76** [comment]
I checked out the dev branch but I am unable to build at all:
![image](https://user-images.githubusercontent.com/11838969/41503500-07813600-718b-11e8-9f0e-4cf00a3ae4cd.png)

Is

**Comment by xz64** [comment]
I pushed changes to the dev branch to resolve the issue. (using cross-env)
