### ISSUE TITLE
Need ability to customize output folder

### ISSUE THREAD

**Issue by johannao76** [xz64/license-webpack-plugin#37]
Tried setting outputFilename to a full path, but this causes the plugin to hang on windows. Is there a workaround for this or a fix coming?

**Comment by xz64** [comment]
outputFilename is tightly integrated with webpack. The plugin does something like  `compilation.assets[outputFilename] = ` to generate an additional asset for the licenses in the webpack build. The actual file is written by webpack and not the plugin. I am not sure if webpack provides any way to add assets with absolute paths to the build, but it seems like it would be against the webpack philosophy to allow that.

You could perhaps copy the file after the build is done.

**Comment by johannao76** [comment]
Yes, I ended up copying the file after the build.
