### ISSUE TITLE
Type definition files getting picked up by the plugin

### ISSUE THREAD

**Issue by johannao76** [xz64/license-webpack-plugin#39]
I am having an issue where I am importing a third party package which has a type definition file as a regular dependency (@types/graphql), and the plugin is returning this package even though this does not really seem to be used by our bundle. I checked the generated webpack stats json and this module is not referenced there at all. Is there a bug in the plugin? Should we exclude *.d.ts files from the output?

**Comment by xz64** [comment]
do you have any sample repository where I can see the issue happen? The plugin should only pick up .js files that are used in the build.

**Comment by xz64** [comment]
The plugin just takes whatever webpack is reporting is used in the bundle. The v2 alpha ( https://github.com/xz64/license-webpack-plugin/tree/dev ) has a feature to exclude packages so you may use that
