### ISSUE TITLE
Suppressing no license file error messages

### ISSUE THREAD

**Issue by 0xs** [xz64/license-webpack-plugin#4]
It would be a nice if it was possible to suppress "no license file" errors because for example many of the Angular 2 packages do not have a license file.

> license-webpack-plugin: Could not find a license file for @angular/core, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/compiler, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/common, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/platform-browser, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/forms, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/http, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/router, defaulting to license name found in package.json: MIT
> license-webpack-plugin: Could not find a license file for @angular/platform-browser-dynamic, defaulting to license name found in package.json: MIT

**Comment by xz64** [comment]
Addressed in commit e0648078b3bb4f7cc52d0757286d27b10ae271bf & published to npm (v0.3.0)
