### ISSUE TITLE
Option to still output license of Unknown Licenses

### ISSUE THREAD

**Issue by bluthen** [xz64/license-webpack-plugin#41]
I was thinking there should be an option to still output the output of the license file if it is unknown.

In LicenseExtractor.js:getLicenseText():
```
if (licenseName === LicenseExtractor.UNKNOWN_LICENSE) {
            return '';
 }
```

Can be something like:
```
if (!this.options.outputUnknown && licenseName === LicenseExtractor.UNKNOWN_LICENSE) {
            return '';
}
```

**Comment by xz64** [comment]
The alpha version has this feature already. Can you please try it out?  It is published as `license-webpack-plugin@next` . Documentation can be found here: https://github.com/xz64/license-webpack-plugin/tree/dev

Specifially, the `handleMissingLicenseText` option handles this scenario

**Comment by bluthen** [comment]
Works well. Nice Job!
