### ISSUE TITLE
v2 alpha release feedback

### ISSUE THREAD

**Issue by xz64** [xz64/license-webpack-plugin#43]
Please leave your feedback for the v2 alpha release here.
There are breaking changes so please make sure to read the project page and migration guides:

Project page: https://github.com/xz64/license-webpack-plugin/tree/dev
Migration guide: https://github.com/xz64/license-webpack-plugin/blob/dev/MIGRATION.md

**Comment by Findus23** [comment]
Hi,

Just a quick feedback (I haven't used the non-alpha version before, so maybe I am doing something wrong)

It seems like `perChunkOutput` doesn't do anything. When I set it to `false`, I still get multiple `chunkname.licenses.txt` files. And when I add `outputFilename: 'licenses.txt'`, I only get one file, but it only contains the licenses of the (probably) last checked chunk.

**Comment by xz64** [comment]
Thanks, this is fixed in v2.0.0-alpha.7

**Comment by xz64** [comment]
2.0.0 is released now
