### ISSUE TITLE
additionalPackages/additionalModules failed to include package

### ISSUE THREAD

**Issue by SeanHayes** [xz64/license-webpack-plugin#47]
With 1.4/2.0.0a, this setting work for several other packages but is failing with the npm font-awesome package. Is there something in it's package.json that would cause it to get skipped?

**Comment by xz64** [comment]
I tested font-awesome 4.7.0 and it works fine on both 1.4/2.0.0a. Note that font-awesome does not contain any license file, so you will not see much output in the generated licenses file.

**Comment by SeanHayes** [comment]
Hmm, seems to be working for me now. Thanks for checking.
