### ISSUE TITLE
addBanner and perChunkOutput settings are switched

### ISSUE THREAD

**Issue by Findus23** [xz64/license-webpack-plugin#48]
Hi, 

I found the reason for the bug I mentioned in https://github.com/xz64/license-webpack-plugin/issues/43

The order here is not the same:

https://github.com/xz64/license-webpack-plugin/blob/dbea85760eff6afe90a2a3dd1e24db8fcaa1452b/src/WebpackCompilerHandler.ts#L11-L20

https://github.com/xz64/license-webpack-plugin/blob/dbea85760eff6afe90a2a3dd1e24db8fcaa1452b/src/LicenseWebpackPlugin.ts#L89-L98

**Comment by xz64** [comment]
Thanks for finding this. I published a fix in v2.0.0-alpha.7
