### ISSUE TITLE
Possibility to ignore licenses for dev-dependencies?

### ISSUE THREAD

**Issue by AnderssonChristian** [xz64/license-webpack-plugin#51]
The legal team at my company wants us to list all licenses for all dependencies found in our build (including sub dependencies). However, I also noticed that licenses for our internal tools are also included (like webpack, loaders, linters, etc) - is there a way to ignore those?

**Comment by xz64** [comment]
It will be hard to ignore transitive dependencies of devDependencies. If you have any ideas on how to handle that kind of scenario let me know.

For now I would recommend you to just configure the plugin to exclude the packages that you don't want to show up.

**Comment by AnderssonChristian** [comment]
Is there any way package-lock.json could help with that?

**Comment by xz64** [comment]
package-lock.json would help but I foresee a lot of edge/ambiguous cases that could arise due to implementing this

To ignore direct devDependencies, you can do it programmatically via the `excludedPackageTest` option.
