### ISSUE TITLE
Compilation modules and chunk parsing

### ISSUE THREAD

**Issue by codepunkt** [xz64/license-webpack-plugin#52]
Hello!

I'm implementing a plugin very much like this for an internal usecase and already have a working version for webpack v3. I'd love to update this to webpack v4, but it seems the way of parsing the included node_modules from the compilation modules that i've used doesn't work anymore.

I've taken a look at your modular approach (mostly `WebpackCompilerHandler`, `WebpackChunkHandler`, `ModuleIterator` and `FileIterator`) to gain insight into how you get from `WebpackCompilation` to the included node_modules.

What i've done so far for my webpack v3 plugin is reading the chunks from the compilation by accessing it's `.chunks` property and then reading the modules of each chunk by either accessing `getModules` or the `modules` property: `chunk.getModules ? chunk.getModules() : chunk.modules`

Then, for every module, i simply read it's context and check if it contains "node_modules" as a string. If it does, it's a file from a node_module so i parse the module from the path (first subdirectory of the deepest node_modules directory in the path).

This seems rather hacky and doesn't work for webpack v4 since a module's `context` is sometimes `null`.

Can you elaborate a bit on how you do it - especially where you found the API documentation in regards to what properties/methods a `WebpackCompilation`, a `WebpackChunk` and a `WebpackModule` have? I'm pretty sure there was a documentation like that, but unfortunately i can't find any for v4.

Any help is appreciated!

**Comment by xz64** [comment]
I couldn't find any API documentation for a lot of the webpack internals. I relied mostly on experimentation and looking at typescript typings files to figure it out.

If you want to detect a package, a less hacky approach I took in v2 of license-webpack-plugin is to keep scanning directories upward until you reach a package.json file. For example, if a file comes from `/a/b/c/d.js`, then the plugin searches first for `/a/b/c/package.json`, `/a/b/package.json` until it reaches filesystem root. You wouldn't want this to happen to your project's `package.json` file though, as that would not be third party code. The plugin relies on webpack's `compiler.context` to detect this situation. I'm not sure if context is ever null in webpack v4 (I know it could be null in previous releases of webpack). If you find that `compiler.context` is null, you could try defaulting it to `process.cwd()` (which is what webpack v4 does internally) as that usually corresponds to your project's "root" directory.



Hope that helps.

**Comment by codepunkt** [comment]
My problem is that `module.context` in v4 can be `null`, while in v3 it always referred to the path or directory of the required/imported file before. What i could do with that is simply search this path for `node_modules` strings, and then take the directory after the last `node_modules` string found in the path (e.g. a file `\mnt\d\projects\licensePlugin\node_modules\a\node_modules\b\c.js` belongs to module `b`).

After doing that, i simply threw out duplicate modules and was basically done - having the node_modules name and path to every included module. From there i can then read the `package.json`, check for `/^licen[cs]e/i` files and more.

It is interesting that you did not find any good documentation as well. I'll probably link this issue and discussion to some webpack folks because i think documentation on this is really really needed.

**Comment by codepunkt** [comment]
My question to webpack authors, contributors and maintainers would be:
What is the best hook and the simplest way with that hook to get a list of every `node_module` that is at least partially compiled into the build output (regardless of webpack settings like chunking or others).
