### ISSUE TITLE
support old package.json license format

### ISSUE THREAD

**Issue by shlomiassaf** [xz64/license-webpack-plugin#54]
It looks like v2 does not support packages with the old license formats...

This feature was added due to #5 
https://github.com/xz64/license-webpack-plugin/blob/v1.5.0/src/LicenseExtractor.ts#L101

Are you planning to support this?

If not, please provide a meaningful error...

For example, I got this error:

```
TypeError: licenseType.indexOf is not a function
```

**Comment by xz64** [comment]
This was fixed in v2.0.2  (see #53). I had forgotten to update the changelog, but it is updated now. Are you using version 2.0.2?

**Comment by xz64** [comment]
Will reopen if it is an issue in 2.0.2. Closing this for now.
