### ISSUE TITLE
@types/webpack-sources

### ISSUE THREAD

**Issue by jeremejevs** [xz64/license-webpack-plugin#58]
`@types/webpack-sources` should be a regular dependency, since `dist/WebpackCompilation.d.ts` depends on it. I understand that it's extra weight for non-TS users, but `@types` packages are very lean, and are comparable to having `<package_name>.d.ts` bundled-in weight-wise.

**Comment by xz64** [comment]
I wouldn't consider WebpackCompilation as part of the public API for license-webpack-plugin and therefore don't see any need to make the webpack-sources types a direct dependency. Can you explain your use case a bit more?

**Comment by jeremejevs** [comment]
My Webpack configs are in TypeScript, and if `@types/webpack-sources` is missing, their type-checking fails. Why Webpack and TypeScript? Because why not? It's a convenient way to catch issues early. For example, it has helped with the v1 to v2 migration.

> I wouldn't consider WebpackCompilation as part of the public API

I have no use for it directly, of course, but [it's depended upon by several other modules](https://github.com/xz64/license-webpack-plugin/search?q=WebpackCompilation&unscoped_q=WebpackCompilation), ending up being a part of `index.ts` anyway.

**Comment by xz64** [comment]
Fixed in v2.0.4

**Comment by jeremejevs** [comment]
Thanks!
