### ISSUE TITLE
TS2322 when using license-webpack-plugin from typescript based webpack config.

### ISSUE THREAD

**Issue by ntdaley** [xz64/license-webpack-plugin#61]
When I have a typescript based webpack config, I get the following typescript error from using license-webpack-plugin:

    error TS2322: Type 'LicenseWebpackPlugin' is not assignable to type 'Plugin'.
      Types of property 'apply' are incompatible.
        Type '(compiler: WebpackCompiler) => void' is not assignable to type '(compiler: Compiler) => void'.
          Types of parameters 'compiler' and 'compiler' are incompatible.
            Property 'context' is missing in type 'Compiler' but required in type 'WebpackCompiler'.

**Comment by xz64** [comment]
I wrote my own typings for the webpack API (in order to support multiple versions of webpack) in license-webpack-plugin. I'll see if I can find a way to support typed webpack configs. By the way, what version of `webpack` and `@types/webpack` are you using?

**Comment by xz64** [comment]
I couldn't figure out any way to resolve this from my end. Supporting multiple webpack versions gets in the way of fixing this. For now you can just cast to `any` to avoid the issue, e.g. `plugins: [ new LicenseWebpackPlugin() as any ]`

**Comment by xz64** [comment]
I believe it supports webpack 2-5. I'm thinking to drop support for webpack versions which are prior to 4.x in a future major release.

**Comment by Austaras** [comment]
Well, I just don't think it's worth it. Webpack 3 is already is 3 years old. Glad to hear you're considering to suppport only webpack 4+
