### ISSUE TITLE
Licenses File does not show all the included dependencies

### ISSUE THREAD

**Issue by jmoranlosada** [xz64/license-webpack-plugin#62]
The legal team at my company wants us to list all licenses for all dependencies found in our build (including transitive dependencies). However, the final results has only a few of the total amount existing.

**Package.json**
 "devDependencies": {
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@storybook/addon-a11y": "^4.1.6",
    "@storybook/addon-actions": "^4.1.6",
    "@storybook/addon-info": "^4.1.6",
    "@storybook/addon-knobs": "^4.1.6",
    "@storybook/addon-options": "^4.1.6",
    "@storybook/preact": "4.2.0-alpha.10",
    "eslint": "^5.1.0",
    "eslint-config-pogo": "^1.0.1",
    "extract-loader": "^3.1.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.1.0",
    "license-webpack-plugin": "^2.1.1",
    "postcss-apply": "^0.12.0",
    "postcss-import": "^12.0.1",
    "postcss-mixins": "^6.2.0",
    "postcss-preset-env": "^5.1.0",
    "preact-render-spy": "^1.2.1",
    "preact-svg-loader": "^0.2.1",
    "preact-transition-group": "^1.1.1",
    "rimraf": "^2.6.3",
    "stylelint": "^9.4.0",
    "workbox-webpack-plugin": "^4.3.1"
  },
  "dependencies": {
    "autobind-decorator": "^2.4.0",
    "classnames": "^2.2.5",
    "intersection-observer": "^0.6.0",
    "preact": "^8.4.2",
    "preact-cli": "3.0.0-rc.1",
    "preact-router": "^2.6.1",
    "smoothscroll-polyfill": "^0.4.4",
    "unistore": "^3.4.1"
  },

**And on my bundle.licenses.txt i only see the following**

@preact/async-loader
autobind-decorator
classnames
intersection-observer
preact-cli
preact-router
preact-transition-group
smoothscroll-polyfill
unistore
webpack

Why am i only able to see these ones and not all the included dependencies?

**Comment by xz64** [comment]
devDependencies are not included as webpack does not report them as being included in your build output. (i.e. there is no code from the devDependencies that went directly into your build output.) If you really want to add them you can use the additionalModules or additionalChunkModules option (see https://github.com/xz64/license-webpack-plugin/blob/master/DOCUMENTATION.md ).
I am not a lawyer, but as far as I know people usually don't report the licenses of their devDependencies.
