### ISSUE TITLE
LicenseTextReader checks for license template inclusion improperly

### ISSUE THREAD

**Issue by emmilco** [xz64/license-webpack-plugin#63]
Here, the package constructs the filename using the license type and `.txt`.

https://github.com/xz64/license-webpack-plugin/blob/d749861e28ffccc2b79e2f95f12615520ddb68ae/src/LicenseTextReader.ts#L57

But if we look at `isFileInDirectory` it's treating that filename as resolvable to a full path, which doesn't work out. 

https://github.com/xz64/license-webpack-plugin/blob/d749861e28ffccc2b79e2f95f12615520ddb68ae/src/WebpackFileSystem.ts#L11

The result being that, currently, the `licenseTemplateDir` option doesn't work.

**Comment by xz64** [comment]
Thank you for the PR. This has been published in v2.1.2
