### ISSUE TITLE
Package name undefined

### ISSUE THREAD

**Issue by Ansimorph** [xz64/license-webpack-plugin#65]
I have an angular project with a npm module that includes a package.json. This file does not set a **name**. The plugin picks this up as **undefined** and then adds a line containing the string »**undefined**« to the end of the 3rdpartylicenses.txt.

I would expect the plugin to print nothing instead of **undefined** if there is no license to match the unknown title.

This happens in the context of an angular CLI project and the offending file is https://github.com/angular/angular/blob/master/packages/common/locales/package.json

The problem occurs in this line of the plugin: https://github.com/xz64/license-webpack-plugin/blob/3ac4744cac36921a3933bd63f635a896f872f2ff/src/PluginFileHandler.ts#L76

This passes on a name even if there is none

**Comment by xz64** [comment]
Thanks for the detailed analysis. The plugin assumes that no one names a file package.json unless that file is an actual package.json intended for npm. I will fix it by checking if the file has a "name" property before deciding to use the package.json. If it doesn't have a "name" property, then it will continue to traverse parent directories until it finds a proper package.json in the directory. In your example, that package.json would be this one: https://github.com/angular/angular/blob/master/packages/common/package.json

**Comment by Ansimorph** [comment]
Perfect. Thanks so much for the quick response!

**Comment by xz64** [comment]
Fixed in version 2.1.3
