### ISSUE TITLE
More modules than dependencies

### ISSUE THREAD

**Issue by omerson** [xz64/license-webpack-plugin#66]
Method **renderLicenses** loads all the dependencies modules plus a few more:

is-buffer
process
setimmediate
timers-browserify
vue-loader
vue-style-loader
base64-js
buffer
ieee754
isarray
moment

I am interested to know what is logic behind this? How does it take some of the transitive dependencies and not all?

**Comment by xz64** [comment]
It's just pulling whatever webpack said was in the build. Some of these libraries inject small snippets into your bundle or were used to transform code. You can use the excludedPackageTest option ( https://github.com/xz64/license-webpack-plugin/blob/master/DOCUMENTATION.md ) to remove these if you want.
