### ISSUE TITLE
Incompatible types

### ISSUE THREAD

**Issue by bennymeg** [xz64/license-webpack-plugin#68]
Hi,

It seems that `LicenseWebpackPlugin` implements `WebpackPlugin` interface,
but `WebpackPlugin` interface is not compatible with Webpack's `Plugin` abstract class.
Which cause my code to break after i have updated from version 1.5.0 to 2.1.3, is their a way to fix it?

**Comment by xz64** [comment]
Looks to be a duplicate of #61, please check there.
