### ISSUE TITLE
Incorrect type for `IncludeExcludeTest`

### ISSUE THREAD

**Issue by jasontbradshaw** [xz64/license-webpack-plugin#70]
Based on the implementation, it seems that the `include` and `exclude` values in https://github.com/xz64/license-webpack-plugin/blob/d41bf38e94484dd5d848056c91d1ecb764415c9c/src/IncludeExcludeTest.ts, currently typed as single-item tuples containing a string, are in fact supposed to be typed as arrays of strings.

I.e. the type should instead be:

```typescript
type IncludeExcludeTest =
  | {
      include?: string[];
      exclude?: string[];
    }
  | ((chunkName: string) => boolean);
```

If I pass these arrays instead of single-item tuples, they seem to work fine with webpack 4.

**Comment by xz64** [comment]
Thanks, I have fixed this in v2.1.4
