### ISSUE TITLE
Problem with thirdparty package (dragscroller)

### ISSUE THREAD

**Issue by tirolel** [xz64/license-webpack-plugin#77]
Thank you for the great plugin.

I just noticed that I keep getting error when importing this package.
https://www.npmjs.com/package/dragscroll

it throws this error: 
"ERROR in WebpackLicensePlugin: Could not find license info for dragscroll@0.0.8"

And here is my config option:
```
  new LicensePlugin({
      outputFilename: 'thirdPartyNotice.json',
      handleMissingLicenseText: (packageName, licenseType) => {
        console.log(`Cannot find license for ${packageName}`);
        return '';
      },
      handleMissingLicenseType: (packageName) => {
        console.log(packageName);
        return '';
      },
    }),
```

am I missing something or it is a bug?

**Comment by xz64** [comment]
dragscroll is missing a license field in its package.json . However the license for that package appears to be MIT, so you can just add an override to the plugin config like this to fix it:

```
new LicenseWebpackPlugin({
  licenseTypeOverrides: {
    dragscroll: 'MIT'
  }
})
```

**Comment by tirolel** [comment]
I see. 
Thank you once again for the awesome work and fast reply.
