### ISSUE TITLE
`@types/webpack-sources` should probably be in `devDependencies`

### ISSUE THREAD

**Issue by silverwind** [xz64/license-webpack-plugin#78]
This module is currently a prod dependency, seems like it's only for dev, right?

**Comment by silverwind** [comment]
Just saw https://github.com/xz64/license-webpack-plugin/issues/58 so this is probably intentional. Seems very odd still to have it as a runtime dependency, maybe TS integration should be reconsidered.

**Comment by xz64** [comment]
It is intentional for those who do webpack configuration in typescript. I agree it's not needed for runtime though.
