### ISSUE TITLE
Unexpected error on empty pattern

### ISSUE THREAD

**Issue by yrtimiD** [xz64/license-webpack-plugin#8]
When patter isn't passed into constructor, plugin tries to report an error:
`245 this.errors.push(plugin.errorMessages['no-pattern']);`
but, at this point this.errors isn't assigned yet, and will be created only at
`248 objectAssign(this, composedPlugin, instance(), opts);`

as result, not very clear error is shown:
```
<redacted>\node_modules\license-webpack-plugin\index.js:245
    this.errors.push(plugin.errorMessages['no-pattern']);
               ^

TypeError: Cannot read property 'push' of undefined
    at new licensePlugin (<redacted>\node_modules\license-webpack-plugin\index.js:245:16)```

**Comment by xz64** [comment]
Thanks, fixed in 0.4.1
