### ISSUE TITLE
Missing `licenseTypeOverides` or typo in documentation

### ISSUE THREAD

**Issue by rickysullivan-gallagher** [xz64/license-webpack-plugin#87]
DOCUMENTATION.md, line ~288 mentions:

> Notes: You can return a license type from this function, but it is a better idea to use the licenseTypeOverides option.

I can't find any config options for `licenseTypeOverides`.

**Comment by xz64** [comment]
Thanks for checking this. It is a typo and should be `licenseTypeOverrides`.  I have pushed a fix.
