### ISSUE TITLE
Error: Chunk.modulesIterable There was no ChunkGraph assigned to the Chunk for backward-compat (Use the new API)

### ISSUE THREAD

**Issue by alan-agius4** [xz64/license-webpack-plugin#88]
When using license-webpack-plugin@2.3.1 with the Webpack 5.10.1 the following error occurs:

```
Error: Chunk.modulesIterable There was no ChunkGraph assigned to the Chunk for backward-compat (Use the new API)
```

I'll try to create a minimal reproduction, if needed.

**Comment by xz64** [comment]
@alan-agius4  Can you try with v2.3.3? I have fixed some deprecation warnings from webpack 5 in this version.

**Comment by alan-agius4** [comment]
Confirmed that it works. Thanks.
