### ISSUE TITLE
Issue with Webpack 5, LicenseWebpackPlugin and HtmlWebpackPlugin 

### ISSUE THREAD

**Issue by tobiasweibel** [xz64/license-webpack-plugin#97]
Hi

I try to upgrade Webpack 4 --> 5 and do have an issue with the LicenseWebpackPlugin in combination with HtmlWebpackPlugin.

It looks like that HtmlWebpackPlugin adds a `chunkModule.resource` value that isn't covered/skipped by LicenseWebpackPlugin.

I see the following `chunkModule.resource` value: `"data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;"` at https://github.com/xz64/license-webpack-plugin/blob/7220854c877579ccebcb3129118796e8c9a60ff9/src/WebpackModuleFileIterator.ts#L11-L14

When I read the code I expect that the following condition should be adapted to return `null` in case `filename` is like the value above. I don't have experience with webpack programming and I'm not really sure how to exclude such a `filename`.
https://github.com/xz64/license-webpack-plugin/blob/7220854c877579ccebcb3129118796e8c9a60ff9/src/WebpackModuleFileIterator.ts#L34-L40

**Comment by xz64** [comment]
Thanks for the report and analysis. This is fixed in v2.3.16

**Comment by tobiasweibel** [comment]
Thanks for the fix! Seems to work.
